"""Read-only view over the residual-gap triage: is each gap real, and still open?

Three artifacts, three provenances, deliberately kept apart so a reader can see
which is which rather than being handed one blended verdict:

``residual_povs/TRIAGE.json``
    generated by ``benchmark/residual_povs/triage/sweep_upstream.py``. Carries the
    machine-collected ``upstream_evidence`` (are the official fix's own lines
    still at upstream HEAD?) plus whatever a human recorded in
    ``residual_povs/triage/verdicts.json``.

``residual_povs/verification/<slug>.json``
    written by ``python -m security_pipeline respov reverify`` — an independent
    *execution* record: the POV was actually run on the unpatched tree, on
    ``buggy + official_fix.patch``, and (where a control revision was given) on
    the later tree upstream fixed it in, where it must flip to ``blocked``.

``residual_povs/<slug>/manifest.json``
    the suite itself: the certification the pipeline scores against, with the
    exploit path and gap summary each POV claims.

The endpoint joins them per POV and reports the join's *state*, never a merged
score: ``status`` is the human verdict, ``upstream_signal`` is the machine lead,
and ``execution`` is what actually ran. A POV can be certified, look open at
HEAD, and still have no execution record — that combination is exactly what an
auditor needs to see, so it is rendered rather than smoothed over.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional

import config

RESIDUAL_DIR = config.residual_povs_dir()
TRIAGE_PATH = RESIDUAL_DIR / "TRIAGE.json"
VERDICTS_PATH = RESIDUAL_DIR / "triage" / "verdicts.json"
VERIFICATION_DIR = RESIDUAL_DIR / "verification"

# Ordered worst-news-first, which is also the order a reviewer wants to audit in.
STATUS_ORDER = [
    "open-at-head", "fixed-later", "superseded-in-release",
    "disputed", "unsound", "needs-manual", "untriaged",
]


def _read_json(path: Path) -> Optional[dict]:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _manifest_index() -> dict[str, dict]:
    """slug -> manifest, for the POV-level detail the triage record does not copy."""
    out: dict[str, dict] = {}
    for path in sorted(RESIDUAL_DIR.glob("*/manifest.json")):
        if path.parent.name == "_template":
            continue
        data = _read_json(path)
        if data:
            out[path.parent.name] = data
    return out


def _verification_index() -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not VERIFICATION_DIR.is_dir():
        return out
    for path in sorted(VERIFICATION_DIR.glob("*.json")):
        data = _read_json(path)
        if data:
            out[data.get("project_slug") or path.stem] = data
    return out


def _pov_detail(manifest: dict, pov_id: str) -> dict:
    for pov in manifest.get("povs", []):
        if pov.get("id") == pov_id:
            validation = pov.get("validation") or {}
            return {
                "description": pov.get("description", ""),
                "exploit_path": pov.get("exploit_path", ""),
                "gap_summary": pov.get("gap_summary", ""),
                "command": pov.get("command", ""),
                "covers_alert_paths": pov.get("covers_alert_paths", []),
                "certified": bool(validation.get("certified")),
                "certified_before": (validation.get("before") or {}).get("outcome"),
                "certified_after": (validation.get("after") or {}).get("outcome"),
                "certified_at": validation.get("ran_at", ""),
                "content_hash": validation.get("content_hash", ""),
            }
    return {}


def overview() -> dict:
    """Every certified residual POV with its triage state, one row per POV."""
    triage = _read_json(TRIAGE_PATH)
    if triage is None:
        return {
            "available": False,
            "reason": (
                "benchmark/residual_povs/TRIAGE.json is missing — generate it with "
                "`python3 benchmark/residual_povs/triage/sweep_upstream.py`"
            ),
            "rows": [], "summary": {},
        }

    manifests = _manifest_index()
    verifications = _verification_index()

    rows: list[dict] = []
    for row in triage.get("povs", []):
        slug = row["project_slug"]
        manifest = manifests.get(slug, {})
        verification = verifications.get(slug, {})
        exec_record = ((verification.get("povs") or {}).get(row["pov_id"])) or row.get("execution") or {}
        evidence = row.get("upstream_evidence") or {}
        rows.append({
            "pov_uid": row["pov_uid"],
            "project_slug": slug,
            "pov_id": row["pov_id"],
            "cve_id": row.get("cve_id", ""),
            "cwe_id": row.get("cwe_id", ""),
            "status": row.get("status", "untriaged"),
            "claim_class": row.get("claim_class", ""),
            "confidence": row.get("confidence", ""),
            "certified": row.get("certified", False),
            "gap_summary": row.get("gap_summary", ""),
            "official_fix_commits": row.get("official_fix_commits", []),
            "official_fix_date": row.get("official_fix_date", ""),
            "later_fix_commit": row.get("later_fix_commit", ""),
            "later_fix_date": row.get("later_fix_date", ""),
            "later_fix_release": row.get("later_fix_release", ""),
            "delta_days": row.get("delta_days"),
            "releases_exposed": row.get("releases_exposed", ""),
            "corroboration": row.get("corroboration", ""),
            "notes": row.get("notes", ""),
            "verified_by": row.get("verified_by", ""),
            "evidence_urls": row.get("evidence_urls", []),
            "upstream_signal": evidence.get("signal", "not_checked"),
            "upstream_repo": evidence.get("repo"),
            "upstream_checked_at": evidence.get("checked_at", ""),
            "upstream_liveness": evidence.get("liveness"),
            "upstream_files": evidence.get("files", []),
            "execution": {
                "ran": bool(exec_record.get("trees")),
                "summary": exec_record.get("summary", ""),
                "falsifiability_control": exec_record.get("falsifiability_control", "not_run"),
                "trees": exec_record.get("trees", {}),
            },
            "pov": _pov_detail(manifest, row["pov_id"]),
        })

    def counted(key: str) -> dict[str, int]:
        out: dict[str, int] = {}
        for row in rows:
            out[row.get(key) or "unknown"] = out.get(row.get(key) or "unknown", 0) + 1
        return dict(sorted(out.items(), key=lambda kv: -kv[1]))

    executed = [r for r in rows if r["execution"]["ran"]]
    controls = [r for r in rows if r["execution"]["falsifiability_control"] == "passed"]
    contradictions = [r for r in rows if r["execution"]["summary"] == "contradicts"]

    return {
        "available": True,
        "generated_at": triage.get("generated_at", ""),
        "note": triage.get("note", ""),
        "rows": sorted(rows, key=lambda r: (
            STATUS_ORDER.index(r["status"]) if r["status"] in STATUS_ORDER else len(STATUS_ORDER),
            r["project_slug"], r["pov_id"],
        )),
        "summary": {
            "povs": len(rows),
            "projects": len({r["project_slug"] for r in rows}),
            "certified": sum(1 for r in rows if r["certified"]),
            "by_status": counted("status"),
            "by_upstream_signal": counted("upstream_signal"),
            "by_claim_class": counted("claim_class"),
            # The three numbers that say how much of this is evidence vs reading.
            "executed": len(executed),
            "falsifiability_controls_passed": len(controls),
            "execution_contradictions": len(contradictions),
        },
    }


def suite(project_slug: str) -> dict:
    """One suite in full: manifest metadata, its POV rows, and its execution record."""
    data = overview()
    if not data["available"]:
        return data
    rows = [r for r in data["rows"] if r["project_slug"] == project_slug]
    if not rows:
        return {"available": False, "reason": f"no residual suite named {project_slug}", "rows": []}
    manifest = _manifest_index().get(project_slug, {})
    verification = _verification_index().get(project_slug)
    return {
        "available": True,
        "project_slug": project_slug,
        "cve_id": manifest.get("cve_id", ""),
        "cwe_id": manifest.get("cwe_id", ""),
        "summary": manifest.get("summary", ""),
        "sink": manifest.get("sink", ""),
        "trust_boundary": manifest.get("trust_boundary", ""),
        "residual_of": manifest.get("residual_of", ""),
        "fix_reference": manifest.get("fix_reference", {}),
        "advisory": manifest.get("advisory", {}),
        "rows": rows,
        "verification": verification,
        # Everything a person needs to redo this by hand, spelled out.
        "reproduce": {
            "certify": f"python -m security_pipeline respov validate --project {project_slug}",
            "reverify": f"python -m security_pipeline respov reverify --project {project_slug}",
            "control": (
                f"python -m security_pipeline respov reverify --project {project_slug} "
                "--skip-baseline --at <later-fix-commit>"
            ),
            "sweep": f"python3 benchmark/residual_povs/triage/sweep_upstream.py --slug {project_slug}",
            "files": f"benchmark/residual_povs/{project_slug}/",
        },
    }
